name: nuget-push

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.+"
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Store version
        env:
          RELEASE_VERSION: ${{github.ref_name}}
        run: |
          echo Version resolved to: $RELEASE_VERSION
      - run: dotnet restore /p:Version=$(RELEASE_VERSION)
      - run: dotnet build --configuration Release --no-restore /p:Version=$(RELEASE_VERSION)
      - run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --no-restore --output .
      - run: dotnet nuget push PortableText.${RELEASE_VERSION}.nupkg --source --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
