name: nuget-push

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+**"
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - run: dotnet restore /p:Version=${{github.ref_name}}
      - run: dotnet build --configuration Release --no-restore /p:Version=${{github.ref_name}}
      - run: dotnet pack --configuration Release /p:Version=${{github.ref_name}} --no-build --no-restore --output .
      - run: dotnet nuget push PortableText.${{github.ref_name}}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
