name: build-and-test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
      - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - run: dotnet test --no-restore --verbosity normal --logger trx --results-directory "testresults"
      - uses: actions/upload-artifact@v3
        with:
          path: testresults
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
